{{- if .Values.extraDeploy }}
---
apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
  labels:
    {{- include "dify.labels" . | nindent 4 }}
items:
{{- toYaml .Values.extraDeploy | nindent 2 }}
{{- end }}