apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dify.sandbox.fullname" . }}
data:
  {{- include "dify.sandbox.config" . | nindent 2 }}
  config.yaml: |-
    {{- include "dify.sandbox.config.conf" . | indent 4 }}
